apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  annotations:
    imageregistry: "https://hub.docker.com/"
    moredet: "this is the test text for testing purpose"
  labels:
    app: flask
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: sreeharshav/flask:v1
          env:
            - name: DEMO_GREETING
              value: "Hello from the environment"
            - name: DEMO_FAREWELL
              value: "Such a sweet sorrow"
          ports:
            - containerPort: 5000
  minReadySeconds: 10
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1

