apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  annotations:
    imageregistry: "https://hub.docker.com/"
    moredet: "this is the test text for testing purpose"
  labels:
    app: flask
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: sreeharshav/flask:v1
          ports:
            - containerPort: 5000
          annotations:
            imageregistry: "https://hub.docker.com/"
            moredet: "this is the test text for testing purpose"


