apiVersion: v1
kind: Pod
metadata:
  labels:
    test: run
  name: nginx
spec:
  containers:
    - name: nginx
      image: sreeharshav/flask:v1
      ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    test: run
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer